# Site settings
title: Your awesome title
search_enabled: false
baseurl: /pages-test
url: https://ashtonmeuser.github.io
permalink: /:title

# Build settings
exclude: [README.md]
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
