# Site settings
title: Your awesome title
search_enabled: false
permalink: /:title

# Build settings
source: src
include: [src]
exclude: [README.md]
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
